version: '3.9'

services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8000"

  flight-service:
    build: ./flight-service
    ports:
      - "8002:8000"

  hotel-service:
    build: ./hotel-service
    ports:
      - "8003:8000"

  booking-service:
    build: ./booking-service
    ports:
      - "8004:8000"

  payment-service:
    build: ./payment-service
    ports:
      - "8005:8000"

  ai-service:
    build: ./ai-service
    ports:
      - "8006:8000"
